=== amitaman01/capability-measure-tool/src/main/resources/raml/schemas/industryMaps/Put-IndustryMap-Request-Schema.json
{
	"$schema": "http://json-schema.org/draft-03/schema",
	"title": "IndustryMap PUT Request Schema",
	"description": "schema to PUT a IndustryMap",
	"type": "object",
	"required": true,
	"properties": {
		"mapId": {
			"type": "string",
			"required": true
		},
		"versionId": {
			"type": "string",
			"required": true
		},
		"sectorId": {
			"type": "string",
			"required": true
		},
		"archiveInd": {
			"type": "string",
			"required": true
		},
		"createDt": {
			"type": "string",
			"required": true
		},
		"lastUpdateDt": {
			"type": "string",
			"required": true
		},
		"mapDesc": {
			"type": "string",
			"required": true
		},
		"mapLastUpdateDt": {
			"type": "string",
			"required": true
		},
		"mapNm": {
			"type": "string",
			"required": true
		},
		"mapStatus": {
			"type": "string",
			"required": true
		},
		"mapTyp": {
			"type": "string",
			"required": true
		},
		"usrNmLastUpd": {
			"type": "string",
			"required": true
		}
	},
	"additionalProperties": false

}

=== amitaman01/capability-measure-tool/src/main/resources/raml/examples/Maps/put-capabilityMap-request-example.json
{
  "mapId": "MP1",
  "versionId": "1",
  "sectorId": "ST23",
  "archiveInd": "N",
  "createDt": "05-11-2016 11:04:07-0400",
  "lastUpdateDt": "05-11-2016 11:04:07-0400",
  "mapDesc": "Education Map",
  "mapLastUpdateDt": "2016-05-11 11:04:07",
  "mapNm": "K-12 Education",
  "mapStatus": "Active",
  "mapTyp": "Industry",
  "usrNmLastUpd": "Dileep"
}
